### ISSUE TITLE
Filebeat lab does not work

### ISSUE THREAD

**Issue by markkerzner** [elephantscale/elastic-labs#20]
https://github.com/elephantscale/elastic-labs/blob/master/movielens/16-filebeat/index.md

To start, this file does not exist, but the one with '2' does
sudo mv /etc/filebeat/modules.d/apache2.yml.disabled /etc/filebeat/modules.d/apache2.yml

(gives error)

Compare to the documentation install

https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration.html

**Comment by mdani38** [comment]
Ok. I will work on it in the morning and sort it out.
