### ISSUE TITLE
Upograde all labs in the movielens directory to 7.5 of elastic/logsash/kibana

### ISSUE THREAD

**Issue by timfox456** [elephantscale/elastic-labs#4]
Go ahead and update this. Yo u don't need to cover install of elastic/logstash/kibana as that is covered already in the install labs at the top level.

**Comment by williamjfermo** [comment]
Movielens Labs 2 to 12 are done.  14 and 15 are done. 13 having issues with logstash tried working on it tonight but thinking it might be my environment, will ask Matt to run through lab, made some changes to lab and may use another install method.   Worked on Beats and xpack I think I am close to getting those to run.

**Comment by markkerzner** [comment]
Thank you. I gave a new fresh environment, new server

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>,
LinkedIn <https://www.linkedin.com/in/markkerzner/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1
Twitter: @elephantscale <https://twitter.com/elephantscale>
